#!/usr/bin/env ruby

intable = false
index = 0

STDIN.each_line do |line|
  if line =~ /Start of API names/
      intable = true
      index = 0
      puts ("// Autogenerated by makeapi.rb")
      puts (".text")
  elsif line =~ /End of API names/
    break
  elsif intable
    if line =~ /.*"(.*)"/
      name = $1
      puts("  .globl #{name}")
      puts("#{name}:")
      puts("  jmp *ruby_fptrs+#{index*8}")
      index += 1
    end
  end
end
