#!/usr/bin/env ruby

intable = false
index = 0

if `uname -p` =~ /i686/
  ptrsize = 4
else
  ptrsize = 8
end

STDIN.each_line do |line|
  if line =~ /const char \*fnames/
    intable = true
    index = 0
    puts ("// Autogenerated by makeapi.rb")
    puts (".text")
  elsif intable && line =~ /};/
    break
  elsif intable
    if line =~ /.*"(.*)"/
      name = $1
      puts("  .globl #{name}")
      puts("#{name}:")
      puts("  jmp *ruby_fptrs+#{index*ptrsize}")
      index += 1
    end
  end
end
