/*
 * Name:	MicroEMACS
 *		Version stamp.
 * Version:	30
 * Last edit:	9-Feb-88
 * By:		Mark Alexander
 *		drivax!alexande
 *
 * This file contains the string(s)
 * that get written out by the show version command.
 * Rich had it generated by a command file. I do
 * it manually, until I can figure out a way to get
 * the MicroEMACS version number generated in a
 * reasonable (automatic) manner. Perhaps a program
 * that reads "things2do.txt".
 */
#include	"def.h"

char *version[] = {
  "MicroEMACS version 30.8, 17-Apr-91",
  "Source from alexande@borland.com",
  NULL
};
